name: Publish

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js v12
      uses: actions/setup-node@v1.1.0
      with:
        version: 12
        registry-url: https://registry.npmjs.org/

    - name: Install dependencies
      run: yarn install
    
    - name: Build project
      run: yarn build
    
    - name: Publish to npm
      run: yarn publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
